HBMStore/src/HBMStore.WebApps.MVC/Models/ErrorViewModel.cs
using System;

namespace HBMStore.WebApps.MVC.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

HBMStore/src/HBMStore.WebApps.MVC/Controllers/Administracao/AdminProdutosController.cs
using HBMStore.Catalogo.Application.Services;
using HBMStore.Catalogo.Application.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Threading.Tasks;

namespace HBMStore.WebApps.MVC.Controllers.Administracao
{
    [Route("admin-produto")]
    public class AdminProdutosController : Controller
    {

        private readonly IProdutoAppService _produtoAppService;

        public AdminProdutosController(IProdutoAppService produtoAppService)
        {
            _produtoAppService = produtoAppService;
        }

        [HttpGet]        
        public async Task<IActionResult> Index()
        {
            return View(await _produtoAppService.ObterTodos());
        }

        [HttpGet]
        [Route("novo-produto")]
        public async Task<IActionResult> NovoProduto()
        {
            return View(await PopularCategorias(new ProdutoViewModel()));
        }

        [HttpPost]
        [Route("novo-produto")]
        public async Task<IActionResult> NovoProduto(ProdutoViewModel produtoViewModel)
        {
            if (!ModelState.IsValid)
                return View(await PopularCategorias(produtoViewModel));

            await _produtoAppService.AdicionarProduto(produtoViewModel);

            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        [Route("editar-produto")]
        public async Task<IActionResult> AtualizarProduto(Guid id)
        {
            return View(await PopularCategorias(await _produtoAppService.ObterPorId(id)));
        }

        [HttpPost]
        [Route("editar-produto")]
        public async Task<IActionResult> AtualizarProduto(Guid id, ProdutoViewModel produtoViewModel)
        {
            var produto = await _produtoAppService.ObterPorId(id);
            produtoViewModel.QuantidadeEstoque = produto.QuantidadeEstoque;

            ModelState.Remove("QuantidadeEstoque");
            if (!ModelState.IsValid) return View(await PopularCategorias(produtoViewModel));

            await _produtoAppService.AtualizarProduto(produtoViewModel);

            return RedirectToAction("Index");
        }

        [HttpGet]
        [Route("produto-atualizar-estoque")]
        public async Task<IActionResult> AtualizarEstoque(Guid id)
        {
            return View("Estoque", await _produtoAppService.ObterPorId(id));
        }

        [HttpPost]
        [Route("produto-atualizar-estoque")]
        public async Task<IActionResult> AtualizarEstoque(Guid id, int quantidade)
        {
            if (quantidade > 0)
            {
                  await _produtoAppService.ReporEstoque(id, quantidade);
            }
            else
            {
                await _produtoAppService.DebitarEstoque(id, quantidade);
            }

            return View(nameof(Index), await _produtoAppService.ObterTodos());
        }

        private async Task<ProdutoViewModel> PopularCategorias(ProdutoViewModel produtoViewModel)
        {
            produtoViewModel.Categorias = await _produtoAppService.ObterCategorias();
            return produtoViewModel;
        }
    }
}

HBMStore/src/HBMStore.WebApps.MVC/Controllers/CarrinhoController.cs
using HBMStore.Catalogo.Application.Services;
using HBMStore.Core.Communication.Mediator;
using HBMStore.Core.Messages.CommomMessages.Notifications;
using HBMStore.Vendas.Application.Commands;
using MediatR;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Threading.Tasks;

namespace HBMStore.WebApps.MVC.Controllers
{
    public class CarrinhoController : ControllerBase
    {
        private readonly IProdutoAppService _produtoAppService;
        private readonly IMediatorHandle _mediatrHandle;

        public CarrinhoController(INotificationHandler<DomainNotification> notification,
                                  IProdutoAppService produtoAppService,
                                  IMediatorHandle mediatorHandler)
                                  : base(notification, mediatorHandler)
        {
            _produtoAppService = produtoAppService;
            _mediatrHandle = mediatorHandler;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        [Route("meu-carrinho")]
        public async Task<IActionResult> AdicionarItem(Guid id, int quantidade)
        {
            var produto = await _produtoAppService.ObterPorId(id);
            if (produto == null)
            {
                return BadRequest();
            }

            if (produto.QuantidadeEstoque < quantidade)
            {
                TempData["Erro"] = "Produto com estoque insuficiente";
                return RedirectToAction("ProdutoDetalhe", "Vitrine", new { id });
            }

            var command = new AdicionarItemPedidoCommand(ClienteId, produto.Id, produto.Nome, quantidade, produto.Valor);

            await _mediatrHandle.EnviarComando(command);

            if (OperacaoValida())
            {
                return RedirectToAction("Index", "Vitrine");
            }

            TempData["Erros"] = ObterMensagensErro();
            return RedirectToAction("ProdutoDetalhe", "Vitrine", new { id });
        }
    }
}

HBMStore/src/HBMStore.WebApps.MVC/Controllers/HomeController.cs
using HBMStore.WebApps.MVC.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace HBMStore.WebApps.MVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

HBMStore/src/HBMStore.WebApps.MVC/Controllers/VitrineController.cs
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using HBMStore.Catalogo.Application.Services;

namespace HBMStore.WebApp.MVC.Controllers
{
    public class VitrineController : Controller
    {
        private readonly IProdutoAppService _produtoAppService;

        public VitrineController(IProdutoAppService produtoAppService)
        {
            _produtoAppService = produtoAppService;
        }

        [HttpGet]
        [Route("")]
        [Route("vitrine")]
        public async Task<IActionResult> Index()
        {
            return View(await _produtoAppService.ObterTodos());
        }

        [HttpGet]
        [Route("produto-detalhe/{id}")]
        public async Task<IActionResult> ProdutoDetalhe(Guid id)
        {
            return View(await _produtoAppService.ObterPorId(id));
        }
    }
}

HBMStore/src/HBMStore.WebApps.MVC/Extensions/SummaryViewComponent.cs
using System.Threading.Tasks;
using MediatR;
using Microsoft.AspNetCore.Mvc;
using HBMStore.Core.Messages.CommomMessages.Notifications;

namespace HBMStore.WebApp.MVC.Extensions
{
    public class SummaryViewComponent : ViewComponent
    {
        private readonly DomainNotificationHandler _notifications;

        public SummaryViewComponent(INotificationHandler<DomainNotification> notifications)
        {
            _notifications = (DomainNotificationHandler)notifications;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var notificacoes = await Task.FromResult(_notifications.ObterNotificacoes());
            notificacoes.ForEach(c => ViewData.ModelState.AddModelError(string.Empty, c.Value));

            return View();
        }
    }
}

HBMStore/src/HBMStore.WebApps.MVC/Views/AdminProdutos/AtualizarProduto.cshtml
@model HBMStore.Catalogo.Application.ViewModels.ProdutoViewModel

@{
    ViewData["Title"] = "AtualizarProduto";
}

<h1>Editar Produto</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="AtualizarProduto">
            <div asp-validation-summary="All" class="text-danger"></div>

            <input type="hidden" asp-for="Id" />

            <div class="form-group">
                <label class="control-label">Categoria</label>
                <select asp-for="CategoriaId" class="form-control" asp-items="@(new SelectList(Model.Categorias, "Id", "Nome"))">
                    <option></option>
                </select>

                <span asp-validation-for="CategoriaId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Descricao" class="control-label"></label>
                <input asp-for="Descricao" class="form-control" />
                <span asp-validation-for="Descricao" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Ativo" /> @Html.DisplayNameFor(model => model.Ativo)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="Valor" class="control-label"></label>
                <input asp-for="Valor" class="form-control" />
                <span asp-validation-for="Valor" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Imagem" class="control-label"></label>
                <input asp-for="Imagem" class="form-control" />
                <span asp-validation-for="Imagem" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Altura" class="control-label"></label>
                <input asp-for="Altura" class="form-control" />
                <span asp-validation-for="Altura" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Largura" class="control-label"></label>
                <input asp-for="Largura" class="form-control" />
                <span asp-validation-for="Largura" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Profundidade" class="control-label"></label>
                <input asp-for="Profundidade" class="form-control" />
                <span asp-validation-for="Profundidade" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Atualizar" class="btn btn-primary" />
                <a class="btn btn-info" asp-action="Index">Voltar</a>
            </div>
        </form>
    </div>
</div>

HBMStore/src/HBMStore.WebApps.MVC/Views/AdminProdutos/Estoque.cshtml
@model HBMStore.Catalogo.Application.ViewModels.ProdutoViewModel
@{
    ViewData["Title"] = "Editar Produto";
}

<div class="container">
    <div class="row">
        <div class="col-xs-4 item-photo">
            <img width="400" height="400" src="~/Images/@Model.Imagem" />
        </div>
        <div class="col-xs-5" style="border:20px solid white">
            <h3>@Model.Nome</h3>

            <h6 class="title-price"><small>OFERTA</small></h6>
            <h3 style="margin-top:0px;">@Model.Valor.ToString("C")</h3>

            <p>Apenas @Model.QuantidadeEstoque em estoque!</p>
            <p>@Model.Descricao</p>

            <div class="section" style="padding-bottom:20px;">
                <form method="post" asp-controller="AdminProdutos" asp-action="AtualizarEstoque">
                    <input type="hidden" id="Id" name="Id" value="@Model.Id" />
                    <input type="text" id="quantidade" name="quantidade" />
                    <button class="btn btn-info">Atualizar Estoque</button>
                </form>
            </div>
        </div>
    </div>
</div>

HBMStore/src/HBMStore.WebApps.MVC/Views/AdminProdutos/Index.cshtml
@model IEnumerable<HBMStore.Catalogo.Application.ViewModels.ProdutoViewModel>

@{
    ViewData["Title"] = "Vitrine";
}
<style>
    h4 {
        font-weight: 600;
    }

    p {
        font-size: 12px;
        margin-top: 5px;
    }

    .price {
        font-size: 30px;
        margin: 0 auto;
        color: #333;
    }

    .right {
        float: right;
        border-bottom: 2px solid #4B8E4B;
    }

    .thumbnail {
        opacity: 0.70;
        -webkit-transition: all 0.5s;
        transition: all 0.5s;
    }

        .thumbnail:hover {
            opacity: 1.00;
            box-shadow: 0px 0px 10px #4bc6ff;
        }

    .line {
        margin-bottom: 5px;
    }

    @@media screen and (max-width: 770px) {
        .right {
            float: left;
            width: 100%;
        }
    }

    .product_view .modal-dialog {
        max-width: 800px;
        width: 100%;
    }

    .pre-cost {
        text-decoration: line-through;
        color: #a5a5a5;
    }

    .space-ten {
        padding: 10px 0;
    }
</style>
<div class="container">

    <h1>Administração de Produtos</h1>
    <hr />
    <div class="row">
        <a asp-controller="AdminProdutos" asp-action="NovoProduto" class="btn btn-success right">+ Adicionar Novo</a>
    </div>
    <hr />
    <div class="row">
        <!-- BEGIN PRODUCTS -->
        @{
            foreach (var produto in Model.OrderBy(p => p.CategoriaId))
            {
            <div class="col-md-3 col-sm-6">
                <span class="thumbnail">
                    <img width="200" height="200" src="~/Images/@produto.Imagem" />
                    <h4>@produto.Nome</h4>
                    <p>@produto.QuantidadeEstoque em estoque</p>
                    <p>@produto.Descricao</p>
                    <p class="price">@produto.Valor.ToString("C")</p>
                    <hr class="line">
                    <div class="row">
                        <a asp-controller="AdminProdutos" asp-action="AtualizarProduto" asp-route-id="@produto.Id" class="btn btn-success right">Editar</a> &nbsp;
                        <a asp-controller="AdminProdutos" asp-action="AtualizarEstoque" asp-route-id="@produto.Id" class="btn btn-info right">Estoque</a>
                    </div>
                </span>
            </div>
            }
        }

        <!-- END PRODUCTS -->
    </div>
</div>

HBMStore/src/HBMStore.WebApps.MVC/Views/AdminProdutos/NovoProduto.cshtml
@model HBMStore.Catalogo.Application.ViewModels.ProdutoViewModel

@{
    ViewData["Title"] = "NovoProduto";
}

<h1>Novo Produto</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="NovoProduto">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">
                <label class="control-label">Categoria</label>
                <select asp-for="CategoriaId" class="form-control" asp-items="@(new SelectList(Model.Categorias, "Id", "Nome"))">
                    <option></option>
                </select>

                <span asp-validation-for="CategoriaId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Descricao" class="control-label"></label>
                <input asp-for="Descricao" class="form-control" />
                <span asp-validation-for="Descricao" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Ativo" /> @Html.DisplayNameFor(model => model.Ativo)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="Valor" class="control-label"></label>
                <input asp-for="Valor" class="form-control" />
                <span asp-validation-for="Valor" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Imagem" class="control-label"></label>
                <input asp-for="Imagem" class="form-control" />
                <span asp-validation-for="Imagem" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="QuantidadeEstoque" class="control-label"></label>
                <input asp-for="QuantidadeEstoque" class="form-control" />
                <span asp-validation-for="QuantidadeEstoque" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Altura" class="control-label"></label>
                <input asp-for="Altura" class="form-control" />
                <span asp-validation-for="Altura" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Largura" class="control-label"></label>
                <input asp-for="Largura" class="form-control" />
                <span asp-validation-for="Largura" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Profundidade" class="control-label"></label>
                <input asp-for="Profundidade" class="form-control" />
                <span asp-validation-for="Profundidade" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Salvar" class="btn btn-primary" />
                <a class="btn btn-info" asp-action="Index">Voltar</a>
            </div>
        </form>
    </div>
</div>

HBMStore/src/HBMStore.WebApps.MVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

HBMStore/src/HBMStore.WebApps.MVC/Views/Shared/Components/Summary/Default.cshtml
@if (ViewData.ModelState.ErrorCount > 0)
{
    <div class="alert alert-danger">
        <button type="button" class="close" data-dismiss="alert">×</button>
        <h3 id="msgRetorno">Opa! Algo deu errado:</h3>
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    </div>
}

@if (TempData["Erro"] != null)
{
    <div class="alert alert-danger">
        <button type="button" class="close" data-dismiss="alert">×</button>
        <h3 id="msgRetorno">Opa! Algo deu errado:</h3>
        <p>@TempData["Erro"]</p>
    </div>
}

@if (TempData["Erros"] != null)
{
    <div class="alert alert-danger">
        <button type="button" class="close" data-dismiss="alert">×</button>
        <h3 id="msgRetorno">Opa! Algo deu errado:</h3>
        @{
            var erros = TempData["Erros"] as string[];
            foreach (var erro in erros)
            {
                <p>@erro</p>
            }
        }

    </div>
}

@if (!string.IsNullOrEmpty(ViewBag.Sucesso))
{
    <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert">×</button>
        <h3 id="msgRetorno">@ViewBag.Sucesso</h3>
    </div>
}

HBMStore/src/HBMStore.WebApps.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HBMStore</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" />
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Vitrine" asp-action="Index">HBMStore</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="AdminProdutos" asp-action="Index">Admin</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - HBMStore - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

HBMStore/src/HBMStore.WebApps.MVC/Views/Vitrine/ProdutoDetalhe.cshtml
@model HBMStore.Catalogo.Application.ViewModels.ProdutoViewModel
@{
	ViewData["Title"] = "Produto Detalhe";
}

<style>
	ul > li {
		margin-right: 25px;
		font-weight: lighter;
		cursor: pointer
	}

	li.active {
		border-bottom: 3px solid silver;
	}

	.item-photo {
		display: flex;
		justify-content: center;
		align-items: center;
		border-right: 1px solid #f6f6f6;
	}

	.menu-items {
		list-style-type: none;
		font-size: 11px;
		display: inline-flex;
		margin-bottom: 0;
		margin-top: 20px
	}

	.btn-success {
		width: 100%;
		border-radius: 0;
	}

	.section {
		width: 100%;
		margin-left: -15px;
		padding: 2px;
		padding-left: 15px;
		padding-right: 15px;
		background: #f8f9f9
	}

	.title-price {
		margin-top: 30px;
		margin-bottom: 0;
		color: black
	}

	.title-attr {
		margin-top: 0;
		margin-bottom: 0;
		color: black;
	}

	.btn-minus {
		cursor: pointer;
		font-size: 7px;
		display: flex;
		align-items: center;
		padding: 5px;
		padding-left: 10px;
		padding-right: 10px;
		border: 1px solid gray;
		border-radius: 2px;
		border-right: 0;
	}

	.btn-plus {
		cursor: pointer;
		font-size: 7px;
		display: flex;
		align-items: center;
		padding: 5px;
		padding-left: 10px;
		padding-right: 10px;
		border: 1px solid gray;
		border-radius: 2px;
		border-left: 0;
	}

	div.section > div {
		width: 100%;
		display: inline-flex;
	}

		div.section > div > input {
			margin: 0;
			padding-left: 5px;
			font-size: 10px;
			padding-right: 5px;
			max-width: 18%;
			text-align: center;
		}

	.attr, .attr2 {
		cursor: pointer;
		margin-right: 5px;
		height: 20px;
		font-size: 10px;
		padding: 2px;
		border: 1px solid gray;
		border-radius: 2px;
	}

		.attr.active, .attr2.active {
			border: 1px solid orange;
		}

	@@media (max-width: 426px) {
		.container {
			margin-top: 0px !important;
		}

			.container > .row {
				padding: 0 !important;
			}

				.container > .row > .col-xs-12.col-sm-5 {
					padding-right: 0;
				}

				.container > .row > .col-xs-12.col-sm-9 > div > p {
					padding-left: 0 !important;
					padding-right: 0 !important;
				}

				.container > .row > .col-xs-12.col-sm-9 > div > ul {
					padding-left: 10px !important;
				}

		.section {
			width: 104%;
		}

		.menu-items {
			padding-left: 0;
		}
	}
</style>
<div class="container">

	<vc:summary />

	<div class="row">
		<div class="col-xs-4 item-photo">

			<img width="400" height="400" src="~/Images/@Model.Imagem" />
		</div>
		<div class="col-xs-5" style="border:20px solid white">
			<h3>@Model.Nome</h3>

			<h6 class="title-price"><small>OFERTA</small></h6>
			<h3 style="margin-top:0px;">@Model.Valor.ToString("C")</h3>

			<p>Apenas @Model.QuantidadeEstoque em estoque!</p>
			<p>@Model.Descricao</p>

			<form method="post" asp-controller="Carrinho" asp-action="AdicionarItem">
				<input type="hidden" id="id" name="id" value="@Model.Id" />

				<div class="section" style="padding-bottom:20px;">
					<h6 class="title-attr"><small>QUANTIDADE</small></h6>
					<div>
						<div class="btn-minus"><span style="font-size: 15px">-</span></div>
						<input style="font-size: 15px" type="text" name="quantidade" value="1" />
						<div class="btn-plus"><span style="font-size: 15px">+</span></div>
					</div>
				</div>

				<!-- Botones de compra -->
				<div class="section" style="padding-bottom:20px;">
					<button class="btn btn-success"><span style="margin-right:20px" aria-hidden="true"></span> Comprar agora!</button>
				</div>

			</form>

		</div>
	</div>
</div>


@section Scripts
{
<script>
	$(document).ready(function(){
		//-- Click on detail
		$("ul.menu-items > li").on("click",function(){
			$("ul.menu-items > li").removeClass("active");
			$(this).addClass("active");
		})

		$(".attr,.attr2").on("click",function(){
			var clase = $(this).attr("class");

			$("." + clase).removeClass("active");
			$(this).addClass("active");
		})

		//-- Click on QUANTITY
		$(".btn-minus").on("click",function(){
			var now = $(".section > div > input").val();
			if ($.isNumeric(now)){
				if (parseInt(now) -1 > 0){ now--;}
				$(".section > div > input").val(now);
			}else{
				$(".section > div > input").val("1");
			}
		})
		$(".btn-plus").on("click",function(){
			var now = $(".section > div > input").val();
			if ($.isNumeric(now)){
				$(".section > div > input").val(parseInt(now)+1);
			}else{
				$(".section > div > input").val("1");
			}
		})
	})
</script>
}